compose_path: /opt/git/augur
compose_file: production-docker-compose.yml

postgres_data_mount_point: "/opt/augur/postgresql/data"
augur_config_data_mount_point: "/opt/augur/config"


augur_pg_container_name: "augur-augur-db-1"
augur_pg_container_user: "augur"
augur_pg_password: "{{ vault_postgres_password }}"
