augur_git_clone_path: /opt/git/augur
compose_path: /opt/compose/augur
compose_file: docker-compose.yml

postgres_data_mount_point: "/opt/augur/postgresql/data"
augur_config_data_mount_point: "/opt/augur/config"


augur_pg_container_name: "augur-augur-db-1"
augur_pg_container_user: "augur"
augur_pg_password: "{{ vault_augur_password }}"

augur_deploy_version: "v0.91.0"
