$ANSIBLE_VAULT;1.2;AES256;prod
31313564633538613664333166623562626336643462643438396434373465653834306164343764
3435343863336337303736353861613239666166396164310a316338633531343231303438613966
34376236613736336133303930633738633361656134303433323235366165336134353639616361
3065373836653137330a373463656561393236323639316532613661303733616561316433383962
65303635636437303164316636396461623033303233643664363737653963343532363437336263
62313534613765353530653361663231323762376530663931633261323230386438613635366564
64316230373166376462646662653434343638613466376665303764653634613134636461396262
31616465343834663932646139336633316166343430303963353838353638303035663933393531
34633439306166653439373866343835396265346665663964343764653162666433626333336139
65353831663538616335646638623033643033313135643264616162343466623034353765626530
32633439643033623062316563343335666462353362306136373264306165356363613538643466
31663237623438616362396236373564326134623461383335613831623461373265383331316236
33383364313033643532663161306535356532373337396366646338636435636666396530393065
64326532656239653839326665613934376333353537666434343534653963613732663465303930
66323730333234336565386137333534666663353534376637643433613234636661343736336437
31383762616635653835643666653331356134303234626537663063623366383834343931653066
62343563613865636231653231306661653034353537343630636238613139623830393538333136
36643533333335663930666265363166313566303537653439663839393133363662326463366438
39303566303265323464616165633336366638666133323533663464616536383264346663333239
37396536383438353434666461336430396530343634386131663466663639323033343737393139
32366538636138316162356432343633643561633264636134333938623634373836666435343633
38623830353634653637303666336134396261323266643531303431333563376433633264633932
39633531373530353661356332623738343935643363383731343739363931356231633739616165
64356533376335313035343366623761633930336163623030623762656162393762653030613235
34303230666631396239663138333733383033336334376232346161626661613665303361633265
36353238633639616162383934656661613136333666643037386336333065306566386263633836
34303830306638316262363835626162343964623235303963636665343938326464343362626531
66326536383232363666616630306237356231346139363036356335613837336336633333626463
61663061656330656337323532333634303262663330326436343137623935326563326462623464
3366303665336436393630356566313564623433663637336536
